#Возможные действия при клике:
#работают локальные плейсхолдеры {player} и {name}(название варпа/точки дома)
#[ACTIONBAR] сообщение
#[MESSAGE] сообщение
#[PLAYER] сообщение (сообщение в чат от имени игрока, для команды от имени игрока /команда)
#[SOUND] Название звука;громкость;тон
#[CONSOLE] команда
#[TITLE] Верхняя строка;Нижняя строка;время появление;время действия;время затухания
#[CLOSE] - закрыть гуи
#[NEXT] - следующая страница
#[PREV] - предыдущая страница
#[UPDATE] - обновить меню
#[REOPEN] - reopen gui
#Все материалы поддерживают basehead-id

colorizer: LEGACY
use-papi: true
decimal-format: "#.#"
event-priority: HIGHEST
no-perms: "&cУ вас недостаточно прав!"
homes-open-commands:
  - /home
  - /homes
warps-open-commands:
  - /warp
  - /warps
preview-open-commands:
  - /kitpreview
actions-on-kit-not-available:
  - '[MESSAGE] &cНабор &6{0} &cне существует!'
#Варпы которые не будут добавляться в меню
black-list-warps:
  - cases
  - pvp
worlds-translations:
  rtp: '&aОбычный'
  world-nether: '&cАдский'
incorrect-uuid: 'Не существует'
homes-menu:
  rows: 6
  title: '&8Точки дома {0}/{1}'
  #Здесь вы можете указать слоты в которые не будут добавляться home-item
  border: 10-16,19,25,28,34,37-43
  #Сколько предметов home-item будет добавляться на 1 страницу
  max-page-items: 10
  home-item:
    material: BOOK
    amount: 1
    name: '&6#{0} &fТочка дома: &6{1}'
    lore:
      - ''
      - '&fКоординаты: &6{2} {3} {4}'
      - '&fМир: {5}'
      - ''
      - '&fЛКМ - Телепортироваться на точку дома'
      - '&fПКМ - Удалить точку дома'
      - ''
    model-data: 0
    enchantments: []
    item-flags: []
    on-left-click:
      - '[PLAYER] /home {0}'
    on-right-click:
      - '[PLAYER] /delhome {0}'
      - '[REOPEN]'
  empty-item:
    material: BARRIER
    amount: 1
    slots: 22
    name: '&cНет точек дома'
    lore: []
    model-data: 0
    enchantments: []
    item-flags: []
    on-left-click: []
    on-right-click: []
  items:
    exit-item:
      slots: 49
      amount: 1
      name: '&cВыйти'
      lore: []
      material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2VkMWFiYTczZjYzOWY0YmM0MmJkNDgxOTZjNzE1MTk3YmUyNzEyYzNiOTYyYzk3ZWJmOWU5ZWQ4ZWZhMDI1In19fQ==
      model-data: 0
      enchantments: []
      item-flags: []
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
    next-page:
      slots: 50
      amount: 1
      name: '&6Следующая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
    prev-page:
      slots: 48
      amount: 1
      name: '&6Предыдущая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
    orange-pane:
      slots: 0-9,17,18,26,27,35,36,44-47,51-53
      name: '&r'
      amount: 1
      lore: []
      material: ORANGE_STAINED_GLASS_PANE
      model-data: 0
      enchantments:
        - MENDING;1
      item-flags:
        - HIDE_ENCHANTS
      on-left-click: []
      on-right-click: []
warps-menu:
  rows: 6
  title: '&8Варпы {0}/{1}'
  border: 10-16,19,25,28,34,37-43
  max-page-items: 10
  warp-item:
    material: BOOK
    amount: 1
    name: '&6#{0} &fВарп: &6{1}'
    lore:
      - ''
      - '&fКоординаты: &6{4} {5} {6}'
      - '&fМир: {2}'
      - '&fВладелец: &6{3}'
      - ''
      - '&fЛКМ - Телепортироваться на варп'
      - ''
    model-data: 0
    enchantments: []
    item-flags: []
    on-left-click:
      - '[PLAYER] /warp {0}'
    on-right-click: []
  empty-item:
    material: BARRIER
    amount: 1
    slots: 22
    name: '&cНет варпов'
    lore: [ ]
    model-data: 0
    enchantments: [ ]
    item-flags: [ ]
    on-left-click: [ ]
    on-right-click: [ ]
  items:
    exit-item:
      slots: 49
      amount: 1
      name: '&cВыйти'
      lore: [ ]
      material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2VkMWFiYTczZjYzOWY0YmM0MmJkNDgxOTZjNzE1MTk3YmUyNzEyYzNiOTYyYzk3ZWJmOWU5ZWQ4ZWZhMDI1In19fQ==
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
    next-page:
      slots: 50
      amount: 1
      name: '&6Следующая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
    prev-page:
      slots: 48
      amount: 1
      name: '&6Предыдущая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
    orange-pane:
      slots: 0-9,17,18,26,27,35,36,44-47,51-53
      name: '&r'
      amount: 1
      lore: [ ]
      material: ORANGE_STAINED_GLASS_PANE
      model-data: 0
      enchantments:
        - MENDING;1
      item-flags:
        - HIDE_ENCHANTS
      on-left-click: [ ]
      on-right-click: [ ]

kitpreview-menu:
  rows: 6
  title: '&8Набор {2} {0}/{1}'
  border: 10-16,19,25,28,34,37-43
  max-page-items: 10
  items:
    exit-item:
      slots: 49
      amount: 1
      name: '&cВыйти'
      lore: [ ]
      material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2VkMWFiYTczZjYzOWY0YmM0MmJkNDgxOTZjNzE1MTk3YmUyNzEyYzNiOTYyYzk3ZWJmOWU5ZWQ4ZWZhMDI1In19fQ==
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
    next-page:
      slots: 50
      amount: 1
      name: '&6Следующая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
    prev-page:
      slots: 48
      amount: 1
      name: '&6Предыдущая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
    orange-pane:
      slots: 0-9,17,18,26,27,35,36,44-47,51-53
      name: '&r'
      amount: 1
      lore: [ ]
      material: ORANGE_STAINED_GLASS_PANE
      model-data: 0
      enchantments:
        - MENDING;1
      item-flags:
        - HIDE_ENCHANTS
      on-left-click: [ ]
      on-right-click: [ ]
    kit:
      slots: 53
      amount: 1
      name: '&cПолучить набор'
      lore: [ ]
      material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2VkMWFiYTczZjYzOWY0YmM0MmJkNDgxOTZjNzE1MTk3YmUyNzEyYzNiOTYyYzk3ZWJmOWU5ZWQ4ZWZhMDI1In19fQ==
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[PLAYER] /kit {0}'
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
      on-right-click:
        - '[PLAYER] /kit {0}'
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'