#Возможные действия при клике:
#работают локальные плейсхолдеры {player} и {name}(название варпа/точки дома)
#[ACTIONBAR] сообщение
#[MESSAGE] сообщение
#[PLAYER] сообщение (сообщение в чат от имени игрока, для команды от имени игрока /команда)
#[SOUND] Название звука;громкость;тон
#[CONSOLE] команда
#[TITLE] Верхняя строка;Нижняя строка;время появление;время действия;время затухания
#[CLOSE] - закрыть гуи
#[NEXT] - следующая страница
#[PREV] - предыдущая страница
#[UPDATE] - обновить меню
#В material есть поддержка basehead-id

#Формат отображения координат
decimal-format: "#.#"
event-priority: HIGHEST
homes-open-commands:
  - /home
  - /homes
warps-open-commands:
  - /warp
  - /warps
#Варпы которые не будут отображаться в меню
black-list-warps:
  - cases
  - pvp
worlds-translations:
  rtp: '&aОбычный'
  world-nether: '&cАдский'
homes-menu:
  rows: 6
  title: '&8Точки дома {current_page}/{pages}'
  #Если вы не хотите чтобы в гуи все свободные слоты заполнялись home-item
  #Укажите здесь слоты В которые будет добавляться пустота
  border: 10-16,19,25,28,34,37-43
  #Сколько предметов точки дома может быть на 1 странице
  max-page-items: 10
  home-item:
    material: BOOK
    amount: 1
    name: '&6#{num} &fТочка дома: &6{name}'
    lore:
      - ''
      - '&fКоординаты: &6{x} {y} {z}'
      - '&fМир: {world}'
      - ''
      - '&fЛКМ - Телепортироваться домой'
      - '&fПКМ - Удалить точку дома'
      - ''
    model-data: 0
    enchantments: []
    item-flags: []
    #Здесь доступен только локальный плейсхолдер {name} т.к в других не вижу никакого смысла
    on-left-click:
      - '[PLAYER] /home {name}'
    on-right-click:
      - '[PLAYER] /delhome {name}'
      - '[CLOSE]'
  items:
    exit-item:
      slots: 49
      amount: 1
      name: '&cВыйти'
      lore: []
      material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2VkMWFiYTczZjYzOWY0YmM0MmJkNDgxOTZjNzE1MTk3YmUyNzEyYzNiOTYyYzk3ZWJmOWU5ZWQ4ZWZhMDI1In19fQ==
      model-data: 0
      enchantments: []
      item-flags: []
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
    next-page:
      slots: 50
      amount: 1
      name: '&6Следующая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
    prev-page:
      slots: 48
      amount: 1
      name: '&6Предыдущая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
    orange-pane:
      slots: 0-9,17,18,26,27,35,36,44-47,51-53
      name: '&r'
      amount: 1
      lore: []
      material: ORANGE_STAINED_GLASS_PANE
      model-data: 0
      enchantments:
        - MENDING;1
      item-flags:
        - HIDE_ENCHANTS
      on-left-click: []
      on-right-click: []
warps-menu:
  rows: 6
  title: '&8Варпы {current_page}/{pages}'
  border: 10-16,19,25,28,34,37-43
  max-page-items: 10
  warp-item:
    material: BOOK
    amount: 1
    name: '&6#{num} &fВарп: &6{name}'
    lore:
      - ''
      - '&fКоординаты: &6{x} {y} {z}'
      - '&fМир: {world}'
      - '&fСоздатель: &6{owner}'
      - ''
      - '&fЛКМ - Телепортироваться на варп'
      - ''
    model-data: 0
    enchantments: []
    item-flags: []
    #Здесь доступен только локальный плейсхолдер {name} т.к в других не вижу никакого смысла
    on-left-click:
      - '[PLAYER] /warp {name}'
    on-right-click: []
  items:
    exit-item:
      slots: 49
      amount: 1
      name: '&cВыйти'
      lore: []
      material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2VkMWFiYTczZjYzOWY0YmM0MmJkNDgxOTZjNzE1MTk3YmUyNzEyYzNiOTYyYzk3ZWJmOWU5ZWQ4ZWZhMDI1In19fQ==
      model-data: 0
      enchantments: []
      item-flags: []
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[CLOSE]'
    next-page:
      slots: 50
      amount: 1
      name: '&6Следующая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[NEXT]'
        - '[UPDATE]'
    prev-page:
      slots: 48
      amount: 1
      name: '&6Предыдущая страница'
      lore: [ ]
      material: ARROW
      model-data: 0
      enchantments: [ ]
      item-flags: [ ]
      on-left-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
      on-right-click:
        - '[SOUND] ENTITY_ENDERMAN_TELEPORT;1.0F;1.0F'
        - '[PREV]'
        - '[UPDATE]'
    orange-pane:
      slots: 0-9,17,18,26,27,35,36,44-47,51-53
      name: '&r'
      amount: 1
      lore: []
      material: ORANGE_STAINED_GLASS_PANE
      model-data: 0
      enchantments:
        - MENDING;1
      item-flags:
        - HIDE_ENCHANTS
      on-left-click: []
      on-right-click: []