name: GreatEssentialsGui
version: '${project.version}'
main: dev.enco.greatessentialsgui.Main
api-version: '1.16'
depend: [Essentials]
author: Encourager
commands:
  greatessentialsgui:
    aliases:
      - gegui
      - essgui
      - essentialsgui